#ifndef GLOBALS_H
#define GLOBALS_H

// Pin definitions
#define UART_TX_ESP32 17
#define UART_RX_ESP32 16
#define ENCODER_A_PIN 34
#define ENCODER_B_PIN 35
#define STEPPER_STEP_PIN 23
#define STEPPER_DIR_PIN 22
#define ENDSTOP_TOP_PLUNGER 19
#define ENDSTOP_BOTTOM_PLUNGER 18
#define ENDSTOP_BARREL_CLAMP_OK 5
#define ENDSTOP_NOZZLE_BLOCK 15
#define TEMP_NOZZLE_VSPI_MISO_DO 12
#define TEMP_NOZZLE_VSPI_MOSI_CS 13
#define TEMP_NOZZLE_VSPI_SCK_CLK 14
#define BUTTON_SELECT_PIN 25
#define BUTTON_UP_PIN 26
#define BUTTON_DOWN_PIN 27
#define WS2812B_BUTTON_LEDS 33
#define WS2812B_RING_LEDS 32
#define EMERGENCY_STOP 0

// Other parameters
#define MOTOR_MAX_SPEED 1000 // Adjust as per motor specs
#define MOTOR_ACCELERATION 20000
#define DEBOUNCE_TIME 50 // ms for button debounce

// Modes
enum OperationMode { CONTINUOUS_MOVE, ENDSTOP_MOVE };

#endif
